location-extraction-handler:
    common-words-file-list:
        - ~/andromeda-data/vocabulary-files/english-lowercase.txt
location-candidate-extractor:
    location-name-prefix-trie-file-list:
        - ~/andromeda-data/indexer-files/google-places-names-prefix-trie.txt
    prefix-trie-ignored-prefixes-file-list:
        - ~/andromeda-data/indexer-files/prefix-trie-ignored-prefix-words.txt
solr-search-handler:
    base-url:
        http://localhost:8983/solr
    prefix-trie-ignored-prefixes-file-list:
        - ~/andromeda-data/indexer-files/prefix-trie-ignored-prefix-words.txt
